Normal = {fg = "#C6BFB9", bg = "#161718"},
Bold = {bold = true},
["@text.strong"] = {link = "Bold"},
Boolean = {fg = "#D6ADEB"},
["@boolean"] = {link = "Boolean"},
BufferLineBackground = {fg = "#C6BFB9", bg = "#161718"},
BufferLineBufferSelected = {fg = "#7DE8B3", bg = "#1D1F20", bold = true},
BufferLineFill = {bg = "#161718"},
BufferLineModified = {fg = "#EF846B"},
BufferLineModifiedSelected = {fg = "#FFBD99"},
Character = {fg = "#5CD699"},
["@character"] = {link = "Character"},
CmpItemAbbr = {fg = "#C6BFB9"},
CmpItemAbbrDeprecated = {fg = "#5E5955", strikethrough = true},
CmpItemAbbrMatch = {fg = "#FFBD99", bold = true},
CmpItemAbbrMatchFuzzy = {fg = "#EF846B"},
CmpItemKind = {fg = "#6EE0F7"},
CmpItemMenu = {fg = "#9E9994"},
ColorColumn = {bg = "#181A1B"},
Comment = {fg = "#817A74"},
gitcommitComment = {link = "Comment"},
gitcommitDiscarded = {link = "Comment"},
gitcommitSelected = {link = "Comment"},
gitcommitUntracked = {link = "Comment"},
["@comment"] = {link = "Comment"},
["@lsp.type.comment"] = {link = "Comment"},
Conditional = {fg = "#7DE8B3"},
["@conditional"] = {link = "Conditional"},
Constant = {fg = "#7DC4E8"},
["@constant"] = {link = "Constant"},
["@lsp.type.enumMember"] = {link = "Constant"},
Cursor = {fg = "#161718", bg = "#FFBD99"},
CursorLine = {bg = "#181A1B"},
CursorLineNr = {fg = "#7DE8B3"},
DashboardCenter = {fg = "#EF846B"},
DashboardFooter = {},
DashboardHeader = {fg = "#6EE0F7"},
DashboardShortcut = {fg = "#7DE8B3"},
Debug = {fg = "#EF846B"},
Define = {fg = "#7DE8B3"},
Delimiter = {fg = "#9E9994"},
["@punctuation.bracket"] = {link = "Delimiter"},
["@punctuation.delimiter"] = {link = "Delimiter"},
["@tag.delimiter"] = {link = "Delimiter"},
DiagnosticError = {fg = "#E77E80"},
DiagnosticHint = {fg = "#7DE8B3"},
DiagnosticInfo = {fg = "#6EE0F7"},
DiagnosticUnderlineError = {sp = "#E77E80", undercurl = true},
DiagnosticUnderlineHint = {sp = "#7DE8B3", undercurl = true},
DiagnosticUnderlineInfo = {sp = "#6EE0F7", undercurl = true},
DiagnosticUnderlineorange = {sp = "#EF846B", undercurl = true},
DiagnosticVirtualTextError = {fg = "#E77E80", bg = "#2D1A1A"},
DiagnosticVirtualTextHint = {fg = "#7DE8B3", bg = "#1F2924"},
DiagnosticVirtualTextInfo = {fg = "#6EE0F7", bg = "#052B33"},
DiagnosticVirtualTextWarning = {fg = "#EF846B", bg = "#322724"},
DiagnosticWarning = {fg = "#EF846B"},
DiffAdd = {bg = "#18623D"},
DiffChange = {bg = "#155879"},
DiffDelete = {bg = "#781718"},
DiffText = {bg = "#2084B6"},
DropBarCurrentContext = {bg = "#2B2E31"},
Error = {fg = "#E77E80"},
["@error"] = {link = "Error"},
ErrorMsg = {fg = "#E77E80"},
Exception = {fg = "#E77E80"},
["@exception"] = {link = "Exception"},
Float = {fg = "#FFBD99"},
["@float"] = {link = "Float"},
FloatBorder = {fg = "#9E9994", bg = "#181A1B"},
FloatTitle = {fg = "#9E9994", bg = "#181A1B"},
FoldColumn = {fg = "#5E5955", bg = "#161718"},
Folded = {fg = "#6EE0F7", bg = "#181A1B"},
Function = {fg = "#7DE8B3"},
["@function"] = {link = "Function"},
["@lsp.type.function"] = {link = "Function"},
["@method"] = {link = "Function"},
GitSignsAdd = {fg = "#5CD699"},
GitSignsChange = {fg = "#7DC4E8"},
GitSignsDelete = {fg = "#E77E80"},
HopNextKey = {fg = "#FFBD99", bold = true},
HopNextKey1 = {fg = "#EF846B", bold = true},
HopNextKey2 = {fg = "#EF846B"},
HopUnmatched = {fg = "#5E5955"},
Identifier = {fg = "#C6BFB9"},
IlluminatedWordRead = {bg = "#2B2E31"},
IlluminatedWordText = {bg = "#2B2E31"},
IlluminatedWordWrite = {bg = "#2B2E31"},
IncSearch = {fg = "#161718", bg = "#5CD699"},
Include = {fg = "#7DE8B3"},
["@include"] = {link = "Include"},
IndentBlanklineChar = {fg = "#9E9994"},
IndentBlanklineContextChar = {fg = "#9E9994"},
Italic = {italic = true},
["@text.emphasis"] = {link = "Italic"},
Keyword = {fg = "#EF846B"},
["@keyword"] = {link = "Keyword"},
["@lsp.type.keyword"] = {link = "Keyword"},
Label = {fg = "#7DE8B3"},
["@label"] = {link = "Label"},
LineNr = {fg = "#5E5955"},
Macro = {fg = "#D6ADEB"},
["@constant.macro"] = {link = "Macro"},
["@function.macro"] = {link = "Macro"},
MoreMsg = {fg = "#7DE8B3"},
NormalFloat = {fg = "#C6BFB9", bg = "#161718"},
NormalNC = {fg = "#5E5955", bg = "#161718"},
Number = {fg = "#D6ADEB"},
["@number"] = {link = "Number"},
NvimTreeCursorLine = {bg = "#222426"},
NvimTreeFolderName = {fg = "#6EE0F7"},
NvimTreeGitDeleted = {fg = "#E77E80"},
NvimTreeGitDirty = {fg = "#EF846B"},
NvimTreeGitNew = {fg = "#7DE8B3"},
NvimTreeImageFile = {fg = "#6EE0F7"},
NvimTreeIndentMarker = {fg = "#5E5955"},
NvimTreeNormal = {bg = "#181A1B"},
NvimTreeRootFolder = {fg = "#7DE8B3", bold = true},
NvimTreeSpecialFile = {fg = "#FFBD99", underline = true},
NvimTreeSymlink = {fg = "#EF846B"},
Operator = {fg = "#E9E6E2"},
["@operator"] = {link = "Operator"},
Pmenu = {fg = "#C6BFB9", bg = "#161718"},
PmenuSbar = {bg = "#222426"},
PmenuSel = {fg = "#E9E6E2", bg = "#161718"},
PmenuThumb = {bg = "#5E5955"},
PreCondit = {fg = "#EF846B"},
PreProc = {fg = "#EF846B"},
Question = {fg = "#6EE0F7"},
Repeat = {fg = "#7DE8B3"},
["@repeat"] = {link = "Repeat"},
Search = {bg = "#2B2E31"},
SignColumn = {bg = "#161718"},
Special = {fg = "#FCD27E"},
SpecialChar = {fg = "#FCD27E"},
["@punctuation.special"] = {link = "SpecialChar"},
["@string.escape"] = {link = "SpecialChar"},
["@string.special"] = {link = "SpecialChar"},
SpecialComment = {fg = "#6EE0F7"},
SpellBad = {sp = "#E77E80", undercurl = true},
SpellCap = {undercurl = true},
SpellLocal = {sp = "#EF846B", undercurl = true},
SpellRare = {sp = "#7DE8B3", undercurl = true},
Statement = {fg = "#EF846B"},
StatusLine = {fg = "#C6BFB9", bg = "#1D1F20"},
StatusLineNC = {fg = "#9E9994", bg = "#181A1B"},
StorageClass = {fg = "#6EE0F7"},
String = {fg = "#FCD27E"},
["@string"] = {link = "String"},
Structure = {fg = "#FFBD99"},
["@lsp.type.struct"] = {link = "Structure"},
TabLine = {fg = "#9E9994", bg = "#181A1B"},
TabLineFill = {bg = "#161718"},
TabLineSel = {fg = "#EF846B", bg = "#1D1F20"},
Tag = {fg = "#E09585"},
["@tag"] = {link = "Tag"},
TelescopeBorder = {fg = "#C6BFB9"},
TelescopeMatching = {fg = "#FFFFFF", bold = true},
TelescopeNormal = {fg = "#CFCCC9", bg = "#161718"},
TelescopePreviewBorder = {fg = "#C6BFB9"},
TelescopePromptBorder = {fg = "#7DE8B3"},
TelescopePromptPrefix = {fg = "#7DE8B3"},
TelescopeResultsBorder = {fg = "#C6BFB9"},
TelescopeSelection = {fg = "#E8E6E3", bg = "#2B2E31"},
Title = {fg = "#FFBD99", bold = true},
["@text.title"] = {link = "Title"},
Todo = {fg = "#161718", bg = "#EF846B"},
["@text.todo"] = {link = "Todo"},
Type = {fg = "#FFBD99"},
["@lsp.type.enum"] = {link = "Type"},
["@lsp.type.interface"] = {link = "Type"},
["@lsp.type.type"] = {link = "Type"},
["@lsp.type.typeParameter"] = {link = "Type"},
["@type"] = {link = "Type"},
Typedef = {fg = "#6EE0F7"},
Underlined = {underline = true},
["@text.underline"] = {link = "Underlined"},
VertSplit = {fg = "#5E5955", bg = "#161718"},
Visual = {bg = "#2B2E31"},
VisualNOS = {bg = "#222426"},
WarningMsg = {fg = "#EF846B"},
WhichKey = {fg = "#FFBD99", bg = "#181A1B"},
WhichKeyBorder = {fg = "#E9E6E2"},
WhichKeyDesc = {fg = "#7DE8B3", bg = "#181A1B"},
WhichKeyFloat = {bg = "#1D1F20"},
WhichKeyGroup = {fg = "#6EE0F7", bg = "#181A1B"},
WhichKeySeparator = {fg = "#9E9994", bg = "#181A1B"},
WhichKeySeperator = {fg = "#9E9994"},
WhichKeyValue = {fg = "#9E9994"},
WinSeparator = {fg = "#5E5955"},
gitcommitBranch = {fg = "#EF846B", bold = true},
gitcommitDiscardedFile = {fg = "#E77E80", bold = true},
gitcommitDiscardedType = {fg = "#EF846B"},
gitcommitHeader = {fg = "#7DE8B3"},
gitcommitSelectedFile = {fg = "#7DE8B3", bold = true},
gitcommitSelectedType = {fg = "#EF846B"},
gitcommitUnmergedFile = {fg = "#E77E80", bold = true},
gitcommitUnmergedType = {fg = "#EF846B"},
gitcommitUntrackedFile = {fg = "#EF846B"},
healthError = {fg = "#E77E80"},
healthSuccess = {fg = "#7DE8B3"},
healthWarning = {fg = "#EF846B"},
["@attribute"] = {fg = "#5CD699"},
["@constant.builtin"] = {},
["@constructor"] = {fg = "#7DE8B3"},
["@field"] = {fg = "#C6BFB9"},
["@function.builtin"] = {fg = "#FFBD99"},
["@keyword.function"] = {fg = "#EF846B"},
["@keyword.operator"] = {fg = "#E77E80"},
["@namespace"] = {fg = "#FFBD99"},
["@lsp.type.namespace"] = {link = "@namespace"},
["@parameter"] = {fg = "#C6BFB9"},
["@parameter.reference"] = {fg = "#9E9994"},
["@lsp.type.parameter"] = {link = "@parameter"},
["@property"] = {fg = "#6EE0F7"},
["@lsp.type.property"] = {link = "@property"},
["@string.regex"] = {fg = "#FCD27E"},
["@symbol"] = {fg = "#EF846B"},
["@tag.attribute"] = {fg = "#5CD699"},
["@text"] = {fg = "#C6BFB9"},
["@text.danger"] = {fg = "#E77E80"},
["@text.literal"] = {fg = "#9E9994"},
["@text.note"] = {},
["@text.orangeing"] = {fg = "#EF846B"},
["@text.strike"] = {strikethrough = true},
["@text.uri"] = {fg = "#6EE0F7", underline = true},
["@type.builtin"] = {fg = "#FFBD99"},
["@variable"] = {fg = "#C6BFB9"},
["@variable.builtin"] = {fg = "#D6ADEB"},
["@lsp.type.variable"] = {link = "@variable"},
